#!/bin/bash

sudo systemctl stop cock

sudo /home/comp/clock2/bin/demo \
	-D 1 \
	--led-rows=32 \
	--led-brightness=50 \
	--led-cols=64 \
	--led-chain=2 \
	"/home/comp/clock2/assets/animations/$1.ppm"

sudo systemctl restart cock
