#!/bin/bash

sudo ~/rpi-rgb-led-matrix/examples-api-use/scrolling-text-example \
  --led-rows=32 \
  --led-cols=64 \
  --led-chain=2 \
  -f '/home/comp/rpi-rgb-led-matrix/fonts/Kset1.bdf' \
  -C 243,133,35 \
  -l 2 \
  -s 2 \
  $1
