#!/bin/bash

sudo systemctl stop cock 

sudo /home/comp/clock2/bin/text-example \
  --led-rows=32 \
  --led-cols=64 \
  --led-chain=2 \
  --led-brightness=50 \
  -f '/home/comp/clock2/assets/fonts/Kset1.bdf' \
  -C 243,133,35 \

sudo systemctl restart cock 

