#!/bin/bash

sudo -E systemctl stop cock

sudo /home/comp/clock2/bin/scrolling-text-example \
  --led-rows=32 \
  --led-cols=64 \
  --led-chain=2 \
  -s 7 \
  -f '/home/comp/clock2/assets/fonts/Kset1.bdf' \
  -C 243,133,35 \
  $1

sudo -E systemctl restart cock
